image: marcoturi/ionic:latest

stages:
  - test
  - deploy


before_script:
  - npm install -g cordova@6.5.0 ionic
  - npm install
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  # very verbose, blows log limit.
  - tar -xvf android-sdk_r24.4-linux.tgz > /dev/null 2>&1
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-26.0.0
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-25
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/26.0.0


cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_web:
  stage: test
  only:
      - master
  script:
    - npm run lint
    - npm run scss-lint
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
    - npm run test
    - npm run build
    - npm run e2e

build_ios:
  stage: deploy
  only:
    - release
  script:
    - ./sh/ionic-login.sh
    - ls
    - npm run ios:release:ci
    - ./sh/ionic-package-ios.sh

build_android:
  stage: deploy
  only:
    - release
  script:
    - ls
    - npm run android:release
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk/


